name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Confirm package-lock.json exists
      - name: Check for package-lock.json
        run: |
          if [ ! -f package-lock.json ]; then
            echo "Error: package-lock.json not found"
            exit 1
          fi

      # Install the latest version of npm to ensure compatibility
      - run: npm install -g npm@latest

      # Try using npm install instead of npm ci temporarily
      - run: npm install

      # Run tests
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      # Confirm package-lock.json exists in the publish step
      - name: Check for package-lock.json
        run: |
          if [ ! -f package-lock.json ]; then
            echo "Error: package-lock.json not found in publish step"
            exit 1
          fi

      # Use npm install for now; switch back to npm ci once the issue is resolved
      - run: npm install

      # Publish to npm
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
